"""empty message

Revision ID: 8fcddbf000a1
Revises: 
Create Date: 2021-02-24 10:25:48.834113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcddbf000a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id_doc', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('speciality', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=6), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id_doc')
    )
    op.create_index(op.f('ix_doctor_email'), 'doctor', ['email'], unique=True)
    op.create_index(op.f('ix_doctor_name'), 'doctor', ['name'], unique=True)
    op.create_table('patient',
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=6), nullable=True),
    sa.Column('address', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_patient')
    )
    op.create_index(op.f('ix_patient_email'), 'patient', ['email'], unique=True)
    op.create_index(op.f('ix_patient_name'), 'patient', ['name'], unique=True)
    op.create_table('appointment',
    sa.Column('id_app', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=True),
    sa.Column('id_docter', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.String(length=50), nullable=True),
    sa.Column('treatment', sa.String(length=50), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_docter'], ['doctor.id_doc'], ),
    sa.ForeignKeyConstraint(['id_patient'], ['patient.id_patient'], ),
    sa.PrimaryKeyConstraint('id_app')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_index(op.f('ix_patient_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_email'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_doctor_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_email'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
