"""empty message

Revision ID: ea11431c3e8e
Revises: 8fcddbf000a1
Create Date: 2021-03-09 21:08:38.998100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea11431c3e8e'
down_revision = '8fcddbf000a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('address', sa.String(length=20), nullable=True))
    op.add_column('doctor', sa.Column('image', sa.BLOB(), nullable=True))
    op.add_column('patient', sa.Column('image', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'image')
    op.drop_column('doctor', 'image')
    op.drop_column('doctor', 'address')
    # ### end Alembic commands ###
